language: python

python:
  - 2.7
  - 3.3
  - 3.4

# TODO: set up a larger test matrix:
# - JS9 versions
# - numpy versions
# - astropy / pyfits versions

before_install:
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get update
  - sudo apt-get install node firefox
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install python-numpy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install python3-numpy; fi
  - pip install astropy
  - pip install pytest selenium

  # `pyjs9` tests need `js9Helper.js` running and `js9basics.html` open
  # TODO: start and stop these from the tests
  - git clone https://github.com/ericmandel/js9.git
  - node js9/js9Helper.js &
  - firefox js9/js9basics.html &
  - sleep 3 # give it some time to start

script:
#  - sudo python setup.py install
  - python setup.py test -a '-v'
